const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Camera3D,
		C3.Plugins.progressbar,
		C3.Plugins.Button,
		C3.Plugins.UserMedia,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Cnds.CompareVar
	];
};
self.C3_JsPropNameTable = [
	{ArrièreplanRépété: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Texte: 0},
	{Texte2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{"8Directions": 0},
	{DéfilerVers: 0},
	{LimitéÀLaScène: 0},
	{fem: 0},
	{Souris: 0},
	{Clavier: 0},
	{Caméra3D: 0},
	{BarreDeProgression: 0},
	{Bouton: 0},
	{MédiaUtilisateur: 0},
	{Plateforme: 0},
	{mehcnat: 0},
	{Projectile: 0},
	{bouleFeu: 0},
	{dialogue: 0},
	{boitedialogue: 0},
	{Texte3: 0},
	{Z: 0},
	{Sprite7: 0},
	{Ancre: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{flouz: 0},
	{vie: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{dialoguee: 0},
	{Argent: 0},
	{Vie: 0}
];

self.InstanceType = {
	ArrièreplanRépété: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texte: class extends self.ITextInstance {},
	Texte2: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	fem: class extends self.ISpriteInstance {},
	Souris: class extends self.IInstance {},
	Clavier: class extends self.IInstance {},
	Caméra3D: class extends self.IInstance {},
	BarreDeProgression: class extends self.IProgressBarInstance {},
	Bouton: class extends self.IButtonInstance {},
	MédiaUtilisateur: class extends self.IWorldInstance {},
	mehcnat: class extends self.ISpriteInstance {},
	bouleFeu: class extends self.ISpriteInstance {},
	dialogue: class extends self.ITextInstance {},
	boitedialogue: class extends self.ISpriteInstance {},
	Texte3: class extends self.ITextInstance {},
	Z: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	flouz: class extends self.ITextInstance {},
	vie: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {}
}